# Generated by Django 4.2.5 on 2023-11-24 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlquimiaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fecha',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 11, 24, 3, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 11, 24, 3, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
